# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, constraints, reflection, tagged, transformers, void }:

cabal.mkDerivation (self: {
  pname = "hask";
  version = "0";
  src = /home/shana/programming/hask;
  buildDepends = [ constraints reflection tagged transformers void ];
  meta = {
    homepage = "http://github.com/ekmett/categories";
    description = "Categories";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
