# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cmdargs, HTTP, network }:

cabal.mkDerivation (self: {
  pname = "PastePipe";
  version = "1.6";
  src = /home/shana/programming/pastepipe;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ cmdargs HTTP network ];
  meta = {
    homepage = "http://github.com/creswick/pastepipe";
    description = "CLI for pasting to lpaste.net";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ fuuzetsu ];
  };
})
