# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cmdargs, HTTP, network, networkUri }:

cabal.mkDerivation (self: {
  pname = "PastePipe";
  version = "1.7";
  src = /home/shana/programming/pastepipe;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ cmdargs HTTP network networkUri ];
  meta = {
    homepage = "http://github.com/Fuuzetsu/pastepipe";
    description = "CLI for pasting to lpaste.net";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ fuuzetsu ];
  };
})
