# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, Cabal, deepseq, filepath, ghcPaths, haddockLibrary
, transformers, xhtml
}:

cabal.mkDerivation (self: {
  pname = "haddock-api";
  version = "2.15.1";
  src = /home/shana/programming/haddock/haddock-api;
  buildDepends = [
    Cabal deepseq filepath ghcPaths haddockLibrary transformers xhtml
  ];
  meta = {
    homepage = "http://www.haskell.org/haddock/";
    description = "A documentation-generation tool for Haskell libraries";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
