# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, binary, dataDefault, lens, mtl, text
, transformersBase, yi, yiLanguage, yiRope
}:

cabal.mkDerivation (self: {
  pname = "yi-agda";
  version = "0.1.0.0";
  src = /home/shana/programming/yi-agda;
  buildDepends = [
    attoparsec binary dataDefault lens mtl text transformersBase yi
    yiLanguage yiRope
  ];
  meta = {
    homepage = "https://github.com/Fuuzetsu/yi-agda";
    description = "Agda mode for Yi";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ fuuzetsu ];
  };
})
