# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, async, attoparsec, base16Bytestring, base32Bytestring
, base64Bytestring, bencoding, bitsExtras, cereal, cerealConduit
, conduit, conduitExtra, convertible, cryptohash, dataDefault
, deepseq, entropy, fastLogger, filepath, hashable, hslogger, hspec
, httpClient, httpConduit, httpTypes, intset, iproute, krpc, lens
, liftedAsync, liftedBase, mmap, monadControl, monadLogger
, monadLoops, mtl, network, optparseApplicative, parallelIo
, prettyClass, PSQueue, QuickCheck, quickcheckInstances, random
, randomShuffle, resourcet, SafeSemaphore, split, splitChannel, stm
, temporary, text, time, transformersBase, unorderedContainers
, vector, pkgs
}:

cabal.mkDerivation (self: rec {
  pname = "bittorrent";
  version = "0.0.0.3";
  src = /home/shana/programming/bittorrent;
  isLibrary = true;
  isExecutable = true;
  doCheck = false;
  configureFlags = if doCheck then [ "-ftesting" ] else [];
  buildDepends = [
    attoparsec base16Bytestring base32Bytestring base64Bytestring
    bencoding bitsExtras cereal cerealConduit conduit conduitExtra
    convertible cryptohash dataDefault deepseq entropy fastLogger
    filepath hashable hslogger httpClient httpConduit httpTypes intset
    iproute krpc lens liftedAsync liftedBase mmap monadControl
    monadLogger mtl network optparseApplicative parallelIo prettyClass
    PSQueue random randomShuffle resourcet SafeSemaphore split
    splitChannel stm text time transformersBase unorderedContainers
    vector
  ];
  testDepends = [
    async bencoding cereal conduit conduitExtra convertible dataDefault
    filepath hspec httpTypes iproute krpc monadLogger monadLoops mtl
    network optparseApplicative QuickCheck quickcheckInstances
    resourcet temporary text time pkgs.screen pkgs.rtorrent
  ];
  meta = {
    homepage = "https://github.com/cobit/bittorrent";
    description = "BitTorrent protocol implementation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
