# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, yi, yiRope }:

cabal.mkDerivation (self: {
  pname = "yi-snippet";
  version = "0.1.0.0";
  src = /home/shana/programming/yi-snippet;
  buildDepends = [ yi yiRope ];
  meta = {
    homepage = "https://github.com/yi-editor/yi-snippet";
    description = "Snippet support for Yi";
    license = self.stdenv.lib.licenses.gpl2;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ fuuzetsu ];
  };
})
