# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, filepath, lens, mtl, ooPrototypes, split, time
, transformersBase, yi, yiLanguage
}:

cabal.mkDerivation (self: {
  pname = "yi-contrib";
  version = "0.9.0";
  src = /home/shana/programming/yi/yi-contrib;
  buildDepends = [
    filepath lens mtl ooPrototypes split time transformersBase yi
    yiLanguage
  ];
  meta = {
    homepage = "http://haskell.org/haskellwiki/Yi";
    description = "Add-ons to Yi, the Haskell-Scriptable Editor";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
