# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, hspec, QuickCheck, criterion, random, dataDefault
, quickcheckInstances, lens, bencoding
, test ? true, bench ? true
}:

let
  en = p: x: (if p then "--enable-" else "--disable-") + x;
in
cabal.mkDerivation (self: {
  pname = "hstorrent";
  version = "0.1.0.0";
  src = /home/shana/programming/hstorrent;
  buildDepends = [ dataDefault quickcheckInstances lens bencoding ];
  testDepends = [ hspec QuickCheck criterion random ];
  doCheck = test;
  extraConfigureFlags = [ (en bench "benchmarks") (en test "tests") ];
  meta = {
    homepage = "https://github.com/hstorrent/hstorrent";
    description = "BitTorrent library in Haskell";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
