# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, binary, dataDefault, filepath, mtl, text, transformersBase
, vector, yi, yiLanguage, yiRope
}:

cabal.mkDerivation (self: {
  pname = "yi-fuzzy-open";
  version = "0.1.0";
  src = /home/shana/programming/yi-fuzzy-open;
  buildDepends = [
    binary dataDefault filepath mtl text transformersBase vector yi
    yiLanguage yiRope
  ];
  meta = {
    homepage = "https://github.com/yi-editor/yi-fuzzy-open";
    description = "Fuzzy open plugin for Yi";
    license = self.stdenv.lib.licenses.gpl2;
    platforms = self.ghc.meta.platforms;
  };
})
