# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dataDefault, freeGame, lens, minioperational, mtl, time
, transformers, vector
}:

cabal.mkDerivation (self: {
  pname = "shakugan-no-haskell";
  version = "0.0.0.0";
  src = /home/shana/programming/shakugan-no-haskell;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    dataDefault freeGame lens minioperational mtl time transformers
    vector
  ];
  meta = {
    homepage = "https://github.com/Fuuzetsu/shakugan-no-haskell";
    description = "Simple game featuring the best character";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
