# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, binary, dataDefault, deepseq, fingertree, highlightingKate
, HUnit, lens, QuickCheck, sodium, tasty, tastyHunit
, tastyQuickcheck, tastyTh, text, vector, vty, criterion, rope
}:

cabal.mkDerivation (self: {
  pname = "y";
  version = "0.1.0.0";
  src = /home/shana/programming/y;
  isLibrary = false;
  isExecutable = true;
  configureFlags = [ "--enable-benchmarks" ];
  buildDepends = [
    binary dataDefault deepseq fingertree highlightingKate lens sodium
    text vector vty criterion rope
  ];
  testDepends = [
    binary dataDefault deepseq highlightingKate HUnit lens QuickCheck
    sodium tasty tastyHunit tastyQuickcheck tastyTh text vector
  ];
  meta = {
    description = "Experiments in writing a text editor with frp core";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
