# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, split, yiLanguage }:

cabal.mkDerivation (self: {
  pname = "yi-emacs-colours";
  version = "0.1.0.0";
  src = /home/shana/programming/yi-emacs-colours;
  buildDepends = [ split yiLanguage ];
  meta = {
    homepage = "https://github.com/yi-emacs-colours";
    description = "Simple mapping from colour names used in emacs to Color";
    license = self.stdenv.lib.licenses.gpl2;
    platforms = self.ghc.meta.platforms;
  };
})
