# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, bindingsDSL, portaudio }:

cabal.mkDerivation (self: {
  pname = "bindings-portaudio";
  version = "0.0.2";
  src = /home/shana/programming/bindings-portaudio;
  buildDepends = [ bindingsDSL ];
  pkgconfigDepends = [ portaudio ];
  meta = {
    description = "Low-level bindings to portaudio library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
