# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, bencoding, filepath, hspec, lens, QuickCheck, temporary
, utf8String
}:

cabal.mkDerivation (self: {
  pname = "rtorrent-state";
  version = "0.1.0.1";
  src = /home/shana/programming/rtorrent-state;
  buildDepends = [ bencoding filepath lens utf8String ];
  testDepends = [
    bencoding filepath hspec QuickCheck temporary utf8String
  ];
  meta = {
    homepage = "http://github.com/Fuuzetsu/rtorrent-state";
    description = "Parsing and manipulation of rtorrent state file contents";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
